version: "3.9"

services: 
    # Sqoop service
    sqoop:
        build: .

    # MySQL service
    mysql:
        image: mysql:latest
        restart: always
        environment: 
            MYSQL_DATABASE: 'testingcoffee'
            MYSQL_USER: 'dkpk'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes: 
            - db-vol:/var/lib/mysql

volumes:
    db-vol:
